### ISSUE TITLE
You should not be able to register a summoner name if it is already registered in the guild.

### ISSUE THREAD

**Issue by njhargis** [njhargis/creamy-cogs#16]

**Comment by will-hedges** [comment]
Is this going to be doable with the Red JSON option, or will we need to go to SQL?

**Comment by njhargis** [comment]
This is easy in red config, I'm using it for check games function as well.
Check docs here:
https://docs.discord.red/en/stable/framework_config.html?highlight=config

**Comment by njhargis** [comment]
Should wait till after #11
