### ISSUE TITLE
Allow user to toggle polling on their account off.

### ISSUE THREAD

**Issue by njhargis** [njhargis/creamy-cogs#18]
1. When registering a summoner, add a boolean field to the saved information of whether or not we are checking their live games, default to true.
2. Create a command within leagueset commands that allows you to toggle this flag for yourself.
3. Within check_games, evaluate this flag while looping through registered_summoners.

**Comment by njhargis** [comment]
Probably better to take this on after #11

**Comment by will-hedges** [comment]
Just started looking at this. I can tie it in with `Zilean` pretty easily I think

**Comment by njhargis** [comment]
i'd like that one to work in a DM with bot and go through all guilds i'm registered in
