### ISSUE TITLE
Calculate refresh timer dynamically

### ISSUE THREAD

**Issue by njhargis** [njhargis/creamy-cogs#25]
Depending on how many registered summoners there are, we should calculate how often we can run the check_games logic without getting close to Riot's throttle limit.
20 requests every 1 second
100 requests every 2 minutes

Anytime new summoner is registered, recalculate.

**Comment by will-hedges** [comment]
If the timer class isn't called Zilean I quit the project

**Comment by will-hedges** [comment]
Let's talk about this sometime since I need to get up to speed on how `check_games` works, but could probably do this after
