### ISSUE TITLE
When shutting down while matches are enabled lots of unclosed sessions.

### ISSUE THREAD

**Issue by njhargis** [njhargis/creamy-cogs#31]

**Comment by will-hedges** [comment]
I think [this line in leaguecog.py](https://github.com/njhargis/creamy-cogs/blob/d04dfe2d3ca0e810662a1719f41bd4fcd460971e/leaguecog/leaguecog.py#L72) is creating an open session that is never closed, and isn't ever used

Will test tonight/tomorrow to confirm

**Comment by njhargis** [comment]
Pretty sure this is shutdown on unload.
https://github.com/njhargis/creamy-cogs/blob/d04dfe2d3ca0e810662a1719f41bd4fcd460971e/leaguecog/blitzcrank.py#L24

It is used for the 'get' function, but I'm actually not 100% sold on that function.
https://github.com/njhargis/creamy-cogs/blob/V3/leaguecog/blitzcrank.py#L43

**Comment by will-hedges** [comment]
How did you do the line preview like that?

**Comment by njhargis** [comment]
I think it auto did it because my URL pointed to a specific commit then line instead of a branch then line. Since commit is static it can preview whereas branch could change so no preview? That’s my guess anyways
