### ISSUE TITLE
Standardizing imports and style guide/PEP8

### ISSUE THREAD

**Issue by will-hedges** [njhargis/creamy-cogs#32]
Nitpicky, but I'm happy to go through and do this. I think we keep going back and forth.

[PEP8 on imports...](https://peps.python.org/pep-0008/#imports) TL;DR:
```
Imports should be grouped in the following order:

1. Standard library imports.
2. Related third party imports.
3. Local application/library specific imports.
```

**Comment by njhargis** [comment]
Sweet, I love nitpicky. Should enforce it via some pre-commit hooks.

**Comment by njhargis** [comment]
Pre-commit hooks installed to follow PEP8 and Black formatting.
