### ISSUE TITLE
Command to remove all of a user's specific data.

### ISSUE THREAD

**Issue by njhargis** [njhargis/creamy-cogs#54]
Title

**Comment by will-hedges** [comment]
Do you see this going under `[p]league` or `[p]leagueset` ? I might stub some of this out so I don't forget to test it with `Zilean`

**Comment by swagbotbilly** [comment]
Looks like this already might be baked-in

https://docs.discord.red/en/stable/red_core_data_statement.html?highlight=delete%20user#how-can-i-delete-data-red-has-about-me
