### ISSUE TITLE
Move all standard API call logic into one function to call.

### ISSUE THREAD

**Issue by njhargis** [njhargis/creamy-cogs#6]
Calling Riot's  API is scattered between multiple functions, simplify and consolidate.

**Comment by lodenrogue** [comment]
What's the ask here? Move all the leaguecog functionality into 1 file?

**Comment by njhargis** [comment]
No, it's to standardize how we call Riot's API into one function that authorizes, etc.  All of the code is in Blitzcrank but broken up into a couple of little functions.

**Comment by njhargis** [comment]
> What's the ask here? Move all the leaguecog functionality into 1 file?

No, it's to standardize how we call Riot's API into one function that authorizes, etc. All of the code is in Blitzcrank but broken up into a couple of little functions.

**Comment by will-hedges** [comment]
Is there a compelling reason to keep the `apistring()` method? I think it would be cleaner generate the full url under `get_riot_url()`

Happy to work on it tonight if you wanna assign it to me

**Comment by njhargis** [comment]
Am I missing something? I don't think that function exists anymore.
