### ISSUE TITLE
Cog Installation Walk-through

### ISSUE THREAD

**Issue by njhargis** [njhargis/creamy-cogs#7]
When this cog is first installed it should force user through a setup.
This setup should help them

1. Setup their API key
2. Let them decide if they want announcements when registered users start games.
3. If they choose yes to 2, help them set an announcement channel.
4. Let user decide if they want gambling on games.
5. If yes and economy is turned off, tell them how to turn it on.

**Comment by njhargis** [comment]
Stubbed this one out, would love you to take it on @swagbotbilly.

**Comment by will-hedges** [comment]
You bet. I had started on a little bit before starting a new repo + rebasing some stuff.

**Comment by will-hedges** [comment]
Forgot to note that I changed Ezreal args to kwargs
